version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run:
          name: Build and cover
          command: ./gradlew verGJF && ./gradlew clean assemble check --stacktrace && ./gradlew check :opentelemetry-all:jacocoTestReport
      - run:
          name: Publish coverage
          command:  bash <(curl -s https://codecov.io/bash)
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
  java9:
    docker:
      - image: circleci/openjdk:9-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - java9-gradle-{{ checksum "build.gradle" }}
      - run:
          name: Build
          command: ./gradlew verGJF &&  ./gradlew clean assemble check --stacktrace
      - save_cache:
          paths:
            - ~/.gradle
          key: java9-gradle-{{ checksum "build.gradle" }}


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - java9
